# Site settings
title: Design Portfolio 
email: scott_baron@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specializing in Jekyll, HTML, CSS, and JavaScript.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: scottbaron
github_username:  scottbaron
facebook_username: scottbaron
permalink: /:categories/:title

links:
  -title: about
  url: /about
  -title: work
  url: /work
  -title: articles
  url: /articles
  -title: hire me
  url: /hire-me

# Build settings
markdown: kramdown